from enum import Enum


class Language(Enum):
    Albanian = "sq"
    Arabic = "ar"
    Catalan = "ca"
    Dutch = "nl"
    Bosnian = "bs"
    Bulgarian = "bg"
    Croatian = "hr"
    Czech = "cs"
    Danish = "da"
    Estonian = "et"
    Finnish = "fi"
    French = "fr"
    German = "de"
    Greek = "el"
    Hungarian = "hu"
    Icelandic = "is"
    Irish = "ga"
    Hebrew = "he"
    Italian = "it"
    Serbian = "sr"
    Lithuanian = "lt"
    Maltese = "mt"
    Macedonian = "mk"
    Norwegian = "no"
    Polish = "pl"
    Portuguese = "pt"
    Romanian = "ro"
    Slovak = "sk"
    Slovenian = "sl"
    English = "en"
    Spanish = "es"
    Swedish = "sv"
    Turkish = "tr"